Readme review
dojo/cli-create-app pull request #140
Opened 2018-02-09 17:15 UTC by tomdye

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Updates the readme according to review

Resolves #139

2018-02-09 17:16 UTC, agubler commented on README.md
>  **WARNING** This is _beta_ software. While we do not anticipate significant changes to the API at this stage, we may feel the need to do so. This is not yet production ready, so you should use at you
We can remove this

2018-02-16 18:05 UTC, dylans requested changes

2018-02-16 18:05 UTC, dylans commented on README.md
> +All the dependencies have been pre-installed using `npm` including two `@dojo/cli` commands; [`@dojo/cli-build-app`](https://github.com/dojo/cli-build-app) and [`@dojo/cli-test-intern`](https://githu
All the dependencies have been pre-installed -> All the dependencies are pre-installed

2018-03-01 23:24 UTC, dylans approved these changes

2018-03-01 23:24 UTC, merged