Add simple `appName` check.
dojo/cli-create-app pull request #74
Opened 2017-04-15 21:04 UTC by lzhoucs

**Type:** bug fix

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

This fix adds a check and ensures empty empty `appName` won't pass through the application flow.

Resolves #73

2017-04-16 04:07 UTC, dylans approved these changes

2017-04-16 07:19 UTC, agubler requested changes
Rather than add our own custom check for this, we should be able to leverage `yargs` here by using `requiresArg: true` in the `register.ts`.

2017-04-16 14:03 UTC, lzhoucs commented
Hi @agubler , thanks for the review. Please correct me if I am wrong. `-n` or (`--name`) is already being registered as a [required argument in register.ts](https://github.com/dojo/cli-create-app/blob/master/src/register.ts#L7), and it is currently already working as expected. For example, if I don't specify `-n` at all `dojo create app foo`, I get an error `Missing required argument: n`.

This PR is trying to address a slightly different issue: #73 which is about `-n` not being properly specified. For example:
- `dojo create app -n` # only specify argument name without a corresponding value
- `dojo create app -name foo` # use `-` instead of `--` when using the full argument `name`. Note instead of treating it as the case of 'missing argument `-n`', yargs sees the `-n` and treats it as the same case as above

So in both cases, `args.name` ends up being an empty string parsed by yargs. I agree with you 100% that it is better to handle it in a more built-in way, however yargs doesn't seem to currently offer the option to further restrict a required argument by length or a pattern yet.

2017-04-16 14:24 UTC, agubler commented
@lzhoucs that just specifies that it's required, but not that an argument after is required. Have you tried `requiresArg` as I suggested?

2017-04-16 21:16 UTC, lzhoucs commented
My apologize @agubler ! You are right. `requiresArg` works perfectly and fixes the issue nicely!

2017-04-18 12:27 UTC, dylans approved these changes

2017-04-29 12:59 UTC, dylans commented
@agubler I think the changes made address your requested changes.

2017-05-02 21:38 UTC, agubler approved these changes

2017-05-02 21:39 UTC, agubler commented
Yup @dylans good to go.

2017-05-02 22:26 UTC, merged